<%@ Page CodeFile="DailyMeeting.aspx.vb" Language="vb" AutoEventWireup="true"Inherits="Telerik.Web.Examples.Editor.EditTemplate.DefaultVB" %>

<%@ Register Assembly="Telerik.Web.UI" Namespace="Telerik.Web.UI" TagPrefix="telerik" %>
<%@ Register TagPrefix="telerik" Namespace="Telerik.Web.UI" Assembly="Telerik.Web.UI" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <title>Daily Meeting Online ( Livel I )</title>
</head>
<body>
    <form id="form1" runat="server">
    <telerik:RadScriptManager runat="server" ID="RadScriptManager1" />
    <telerik:RadGrid ID="MyDataGrid" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource1"
        AllowAutomaticUpdates="True" AllowAutomaticDeletes="True" AllowAutomaticInserts="True"
        AutoGenerateEditColumn="True" AutoGenerateDeleteColumn="True" 
        AllowFilteringByColumn="True" AllowPaging="True" AllowSorting="True" 
        CellSpacing="0" GridLines="None" PageSize="5" ShowGroupPanel="True">
        <ClientSettings AllowDragToGroup="True">
        </ClientSettings>
        <MasterTableView DataKeyNames="ID" CommandItemDisplay="Top">
<CommandItemSettings ShowExportToExcelButton="true"></CommandItemSettings>

<RowIndicatorColumn Visible="True" FilterControlAltText="Filter RowIndicator column"></RowIndicatorColumn>

<ExpandCollapseColumn Visible="True" FilterControlAltText="Filter ExpandColumn column"></ExpandCollapseColumn>
            <Columns>
                <telerik:GridTemplateColumn UniqueName="ID" Display="false">
                    <ItemTemplate>
                        <asp:Label ID="IdLabel" runat="server" Text='<%# Eval("ID") %>'></asp:Label>
                    </ItemTemplate>
                </telerik:GridTemplateColumn>
                <telerik:GridDateTimeColumn FilterControlAltText="Filter StartDate column" 
                    HeaderText="Date" UniqueName="StartDate" DataType="System.DateTime" 
                    DataField="StartDate" DataFormatString="{0:dd/MM/yyyy}">
                    <HeaderStyle Font-Bold="True" HorizontalAlign="Center" />
                </telerik:GridDateTimeColumn>
                <telerik:GridRatingColumn FilterControlAltText="Filter Priority column" 
                    HeaderText="Priority" UniqueName="Priority" DataField="Priority" 
                    DataType="System.Decimal">
                    <HeaderStyle Font-Bold="True" HorizontalAlign="Center" />
                </telerik:GridRatingColumn>
                <telerik:GridHTMLEditorColumn DataField="Problem" 
                    FilterControlAltText="Filter Problem column" HeaderText="Problem" 
                    UniqueName="Problem">
                    <HeaderStyle Font-Bold="True" HorizontalAlign="Center" />
                </telerik:GridHTMLEditorColumn>
                <telerik:GridHTMLEditorColumn DataField="Identification" 
                    FilterControlAltText="Filter Indentification column" 
                    HeaderText="Identification" UniqueName="Identification">
                    <HeaderStyle Font-Bold="True" HorizontalAlign="Center" />
                </telerik:GridHTMLEditorColumn>
                <telerik:GridHTMLEditorColumn DataField="CorrectiveAction" 
                    FilterControlAltText="Filter CorrectiveAction column" 
                    HeaderText="CorrectiveAction" UniqueName="CorrectiveAction">
                    <HeaderStyle Font-Bold="True" HorizontalAlign="Center" />
                </telerik:GridHTMLEditorColumn>
                <telerik:GridDateTimeColumn FilterControlAltText="Filter DueDate column" 
                    HeaderText="DueDate" UniqueName="DueDate" DataType="System.DateTime" 
                    DataField="DueDate" DataFormatString="{0:dd/MM/yyyy}">
                    <HeaderStyle Font-Bold="True" HorizontalAlign="Center" />
                </telerik:GridDateTimeColumn>
                <telerik:GridDropDownColumn DataField="PIC" 
                    FilterControlAltText="Filter PIC column" HeaderText="PIC" UniqueName="PIC" 
                    DataSourceID="DS_PIC" ListTextField="Nama" 
                    ListValueField="Email">
                    <HeaderStyle Font-Bold="True" HorizontalAlign="Center" />
                </telerik:GridDropDownColumn>
                <telerik:GridAttachmentColumn FileName="attachment" 
                    FilterControlAltText="Filter Attch column" HeaderText="Attch" 
                    UniqueName="Attch" AllowFiltering="False" DataTextField="Attch" 
                    Display="False">
                    <HeaderStyle Font-Bold="True" HorizontalAlign="Center" />
                </telerik:GridAttachmentColumn>
                <telerik:GridDropDownColumn DataField="Status" DataSourceID="DS_Status" 
                    FilterControlAltText="Filter Status column" HeaderText="Status" 
                    ListTextField="Status" ListValueField="Status" UniqueName="Status">
                    <HeaderStyle Font-Bold="True" HorizontalAlign="Center" />
                </telerik:GridDropDownColumn>
            </Columns>

<EditFormSettings>
<EditColumn FilterControlAltText="Filter EditCommandColumn column"></EditColumn>
</EditFormSettings>
        </MasterTableView>

        <ExportSettings>
            <Excel Format="Biff"></Excel>
        </ExportSettings>

<FilterMenu EnableImageSprites="False"></FilterMenu>
    </telerik:RadGrid>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:MeetingConnectionString %>"
        SelectCommand="SELECT [ID]
,[Priority]
      ,[Problem]
      ,[Identification]
      ,[CorrectiveAction]
      ,[Attch]
      ,[StartDate]
      ,[DueDate]
      ,[PIC]
      ,[UserUpdate]
      ,[TimeUpdate]
,[Status]
  FROM [DB_MEETING].[dbo].[tblDailyMeeting]
where Deleted = 0" UpdateCommand="UPDATE [DB_MEETING].[dbo].[tblDailyMeeting]
   SET [Problem] = @Problem
      ,[Identification] = @Identification
      ,[CorrectiveAction] = @CorrectiveAction
      ,[Attch] = @Attch
      ,[StartDate] = @StartDate
      ,[DueDate] = @DueDate
      ,[PIC] = @PIC
      ,[UserUpdate] = @UserUpdate
      ,[TimeUpdate] = GETDATE()
      ,[Status] = @Status
      ,[Priority] = @Priority
 WHERE ID = @ID"
        
        
        DeleteCommand="UPDATE [DB_MEETING].[dbo].[tblDailyMeeting]
   SET [Deleted] = 1
 WHERE ID = @ID" InsertCommand="INSERT INTO [DB_MEETING].[dbo].[tblDailyMeeting]
           ([Priority]
	   ,[Problem]
           ,[Identification]
           ,[CorrectiveAction]
           ,[Attch]
           ,[StartDate]
           ,[DueDate]
           ,[PIC]
           ,[UserUpdate]
           ,[TimeUpdate]
	   ,[Status])
     VALUES
           (@Priority
	   ,@Problem
           ,@Identification
           ,@CorrectiveAction
	   ,@Attch
           ,@StartDate
           ,@DueDate
           ,@PIC
           ,@UserUpdate
           ,GETDATE()
	   ,'NoProgress')" 
        
        
        
        ProviderName="<%$ ConnectionStrings:MeetingConnectionString.ProviderName %>">
        <DeleteParameters>
            <asp:Parameter Name="ID" Type="Int32"></asp:Parameter>
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="Problem" Type="String"></asp:Parameter>
            <asp:Parameter Name="Identification" Type="String" />
            <asp:Parameter Name="CorrectiveAction" Type="String" />
            <asp:Parameter Name="StartDate" Type="DateTime" />
            <asp:Parameter Name="DueDate" Type="DateTime" />
            <asp:Parameter Name="PIC" Type="String" />
            <asp:SessionParameter DefaultValue="SYSTEM" Name="UserUpdate" 
                SessionField="UserID" Type="String" />
            <asp:Parameter Name="Priority" Type="Decimal" />
            <asp:Parameter Name="Status" Type="String" />
            <asp:Parameter Name="Attch" Type="Byte" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="ID" Type="Int32"></asp:Parameter>
            <asp:Parameter Name="Problem" Type="String"></asp:Parameter>
            <asp:Parameter Name="Identification" Type="String" />
            <asp:Parameter Name="CorrectiveAction" Type="String" />
            <asp:Parameter Name="StartDate" Type="DateTime" />
            <asp:Parameter Name="DueDate" Type="DateTime" />
            <asp:Parameter Name="PIC" Type="String" />
            <asp:SessionParameter DefaultValue="SYSTEM" Name="UserUpdate" 
                SessionField="UserID" Type="String" />
            <asp:Parameter Name="Attch" Type="Byte" />
            <asp:Parameter Name="Status" Type="String" />
            <asp:Parameter Name="Priority" Type="Decimal" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="DS_PIC" runat="server" ConnectionString="<%$ ConnectionStrings:MeetingConnectionString %>"
        SelectCommand="SELECT     Persis.dbo.tblKaryawan.Nrp, Persis.dbo.tblKaryawan.Nama, Persis.dbo.tblKaryawan.Departemen, Persis.dbo.tblKaryawan.Jabatan, Persis.dbo.tblKaryawan.Lokasi, 
                      Persis.dbo.tblKaryawan.Email
FROM         Persis.dbo.tblKaryawan INNER JOIN
                      dbo.tblPIC ON Persis.dbo.tblKaryawan.Nrp = dbo.tblPIC.NRP COLLATE SQL_Latin1_General_CP1_CI_AS" 
        
        
        
        
        ProviderName="<%$ ConnectionStrings:MeetingConnectionString.ProviderName %>">
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="DS_Status" runat="server" ConnectionString="<%$ ConnectionStrings:MeetingConnectionString %>"
        SelectCommand="SELECT 'NoProgress' AS Status
UNION ALL
SELECT 'Open' AS Status
UNION ALL
SELECT 'Close' AS Status" 
        
        
        
        ProviderName="<%$ ConnectionStrings:MeetingConnectionString.ProviderName %>">
    </asp:SqlDataSource>
    </form>
</body>
</html>